### PR TITLE
Refactoring and Features

### PR DESCRIPTION
**Pull request by ghophp**
Hallo... First of all I hope that this PR doesn't sound like a intromission :) I already contributed to open source projects that doesn't receive very good outside contributions.

I had the first contact with the library of communication with TV at my interview process with @ElliDy, and since that I thought that a few improvements could be done to accomplish what I see as a more mature version.

I saw an opened PR made by @meedheym, and since the refactoring and changes I've done are substantially big, I adapt the @meedheym code to this PR covering the behavior of targeting UUID.

Before start reading this CHANGELOG, please take a look, and let a tab of your browser open at the new doc of the code [here](http://ghophp.github.io/samples/yetu-tv-client/docs/yetu-tv-message-client.html).

So, let's see what concerned me at the beginning and what I've done to solve it, based on which material :)
##### Module Pattern :key:

First the scope and namespace are too open for a library, leaving a margin to a conflict, or bad behavior at production level, the pattern I'm proposing was applied on the biggest js libraries nowadays, such as [BackboneJS](http://backbonejs.org/docs/backbone.html) and [UnderscoreJS](http://underscorejs.org/docs/underscore.html).

let's see how I've change it:

``` javascript
(function(flyer, JSON) {

}.call(this, flyer, JSON));
```

With this pattern the _yetu namespace will be attached to the window that will be the `this` inside the context.
##### AMD :gift:

To allow the fans of AMD to use the library, even with [discussions](http://tomdale.net/2012/01/amd-is-not-the-answer/) on the web regarding if the use of AMD is good, I've added the following piece of code at the end of the namespace:

``` javascript
// AMD registration happens at the end for compatibility with AMD loaders
// that may not enforce next-turn semantics on modules. Even though general
// practice for AMD registration is to be anonymous, yetu registers
// as a named module because, it is a base library that is can be bundled 
// in a third party lib, but not be part of an AMD load request. 
// Those cases could generate an error when an
// anonymous define() is called outside of a loader request.
if (typeof define === 'function' && define.amd) {
    define('underscore', [], function() {
        return _yetu;
    });
}
}
```
##### Common Specifications :cool:

There are a few conventions when looking to js libraries that are common code to be written. Such as the `VERSION` variable at the namespace, the start of the namespace with `$` or `_`, a wrapper, a safe reference to the object, a segmentation between what is private and what is public, and a few more things. For this you can take a look into the general code and you will find things such as:

``` javascript
_yetu.VERSION = '1.1.0';
```

``` javascript
// Create a safe reference to the Yetu object for use below.
var _yetu = function(obj) {
    if (obj instanceof _yetu) return obj;
    if (!(this instanceof _yetu)) return new _yetu(obj);
    this._wrapped = obj;
};

// Extracts the result from a wrapped and chained object.
_yetu.prototype.value = function() {
    return this._wrapped;
};
```
##### Clean way to deal with binding :dart:

At the first version of the library I saw a repetition of the same code oftentimes. Witch has a huge impact on how future implementations (such as the @meedhym UUID implementation) are done, and how to use the library. So, based on a more clean approach, I suggest the following behavior:
- _yetu has no handlers at the start
- use `on` method to bind to a specific action
- actions are mapped through "constants" (javascript doesn't have it.. but ok.)
- any action can be listened injecting a `middleware` with `_yetu.any(callback)`
- `handlers` stores and match the action through the `indexOf` ECMA5 customization

I'll not paste the code here, because I strongly recommend the visit to the [hosted doc](http://ghophp.github.io/samples/yetu-tv-client/docs/yetu-tv-message-client.html) version that I presented at the beginning of the PR description. Look into the following: `_yetu.on`, `_yetu.any`, `send`, `handlers`, `receive`.
##### UUID RFC4122 :zzz:

At this point I'm already looking as a "pain in the ass", and this section title is not helping :+1: .. To implement the UUID targeting I've used a method based on the RF4122 that specifies how a UUID should look and be generated. The method will collide in something about 10 thousand years.

``` javascript
// generate a 36 characters UUID (10.000+ year to collision)
// in compliance with the RFC4122
var uuid = function () {
    var d = new Date().getTime();
    var id = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
        var r = (d + Math.random()*16)%16 | 0;
        d = Math.floor(d/16);
        return (c=='x' ? r : (r&0x3|0x8)).toString(16);
    });
    return id;
};
```

The important thing to look here, is that the process of developing the `UUID targeting feature` was easy after the `clean binding behavior`.
##### Example look-and-feel :performing_arts:

First I put jquery in the list of devDependencies of bower, so we can use it to write the example without compromise the final package size or any other branch of the project. The use of jquery or any other framework to write examples is better then raw javascript, maybe we can even write a sample using AMD and angular, because those are the frameworks expected when a 3d-party developer start an application at yetu experience.

SampleApp

I think this is important to give the developer the idea of pressing the remote control. This is why I have implemented the buttons over the remote control image. Maybe an insight could happen to improve the way user interact with the remote control as more as you use it.
##### Tests :ok_hand:

As consequence of the refactoring process, the tests are strongly modified and the coverage was improved:
- Statements: 85.87%    (79 / 92)
- Branches: 60.61%  (20 / 33)
- Functions: 75.00% (15 / 20)
- Lines: 87.64% (78 / 89)
##### Docs with Docco :sparkles:

As notice if you have visited the documentation till this moment, I've used the Docco library to generate the documentation. I think this is a strong tool to js docs, beside the pretty look-and-feel, the code could be complete understood because the strong use of inline comments explaining basically each line and definition.

The docs will be automatically generated as you type `gulp build`. At the README.md you can see a new step that requires the installation of `docco` globally. [Here](http://ghophp.github.io/samples/yetu-tv-client/docs/yetu-tv-message-client.html) is the link to take a look at the result.

### CODE REVIEW

**Comment by mr-mig** [comment]
Nice job, LGTM :+1:

Some considerations for the future:
1. AMD is good, but https://github.com/umdjs/umd will be even better.
2. Assume that browser's `window` is the degraded case, i.e. use UMD :lollipop: 
3. In addition to `yetu.clean` method, `yetu.on` should return an unsubscribe handler
4. Consider replacing event-based API with signals-based API (similar to http://millermedeiros.github.io/js-signals/)
5. Consider bower and npm support.
6. Consider adding UUID generation as a dependency module (not a code inside the lib)

**Comment by ghophp** [comment]
Hello @mr-mig .. thank you for your comment.. really interesting points.. I will look at each one as soon as I get some time to work on that.. maybe this week.. 

@ElliDy and @meedheym if you can give an option at the general PR and also the comments that @mr-mig did, please, this will help the flow :+1: 

I really liked the the ideia of js-signals.. just need to look at the library stability/confidence.. also the UMD was a fantastic mention.. at bower I think we just need to make an `bower register` now... really good mention there.. will look into some UUID generation library, if you can give me some tips.. will be awesome..

**Comment by ghophp** [comment]
I've found this nice package for handle the UUID generation and validation: https://github.com/lil-js/uuid - 1KB UUID package..

And looking into the UMD, this is the common global definition of a module:

``` javascript
(function (root, factory) {
  if (typeof exports === 'object') {
    // CommonJS
    module.exports = factory(require('b'));
  } else if (typeof define === 'function' && define.amd) {
    // AMD
    define(['b'], function (b) {
      return (root.returnExportsGlobal = factory(b));
    });
  } else {
    // Global Variables
    root.returnExportsGlobal = factory(root.b);
  }
}(this, function (b) {
  // Your actual module
  return {};
}));
```

Still looking into the others suggestions.. but those two will be implemented for sure :+1:

**Comment by dev-tim** [comment]
:+1: Looked through PR, good work. Yep, UMD is quite important in order to use it with require, bower or webpack.

**Comment by ghophp** [comment]
well.. the uuid is now generated by lil-uuid.. I leaved a wrapper to the uuid generation.. so.. if we feel the need to change this generation, should be easy.. also.. I wrote a UMD compliance factory.. so now.. it's in compliance with AMD, CommonJS, RequireJS and the browser...

**Comment by ghophp** [comment]
just added the unsubscribe feature.. thank you for the hint @mr-mig.. really missing feature.. so.. it's called `_yetu.off(topic)`.. the test was written.. and the docs updated..

**Comment by ElliDy** [comment]
Hi guys, I add a next steps section to the master branch. I think, this is the way we should go with the two pull requests, because we have already one partner using the master-status. That´s why we need versioning now. Do you think this as well?

**Comment by ghophp** [comment]
@ElliDy good idea.. with bower, the partners will be able to keep their version and avoid a lot of rewriting due to the changes regarding the way you use the library.. and off course.. we will be able to move to a new version.. when do you intend to do those changes?

**Comment by larsblumberg** [comment]
@ghophp Any reason you close this PR without providing a way for merging it?

**Pull request closed without merging**
